apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso1920-messagelistener-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso1920-messagelistener
  template:
    metadata:
      labels:
        app: rso1920-messagelistener
    spec:
      containers:
      - image: rso1920/messagelistener:latest
        name: rso1920-messagelistener
        env:
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://10.0.2.70:8080
          - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
            value: http://etcd:2379/health
        ports:
        - containerPort: 8091
          name: server-messagelistener
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: rso1920-messagelistener
spec:
  type: LoadBalancer
  ports:
  - port: 8091
    protocol: TCP
    targetPort: server-messagelistener
  selector:
    app: rso1920-messagelistener
